[package]
name = "try-rs"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "try"
path = "try.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27"
chrono = "0.4"
regex = "1.10"
dirs = "5.0"
anyhow = "1.0"
directories = "5.0"
